version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/prql/prql
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: run build
          command: |
            dep ensure
            go build -v
      - run:
          name: run tests
          command: |
            make test-prqld
            make test-prql
  deploy:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/prql/prql
    steps:
      - checkout
      - run:
          name: cross compile
          command: |
            make release
      - add_ssh_keys
      - run:
          name: create release
          command: |
            echo 'Release later'
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
